REM here you can put in all file extensions you want to track with git lfs
git lfs track *.fbx
git lfs track *.png
git lfs track *.jpg
git lfs track *.jpeg
git lfs track *.hdr
git lfs track *.exr
git lfs track *.mp3
git lfs track *.wav
git lfs track *.mp4
git lfs track *.mov
git lfs track *.psd
git lfs track *.mb
git lfs track *.tga
git lfs track *.cubemap
git lfs track *.tif
git lfs track *.bin.fbx
git lfs track *.uasset
git lfs track *.umap
git lfs track *.upk
git lfs track *.udk
git lfs track *.duf
git lfs track *.blend
